version: "3.8"

services:
  redis:
    image: redis/redis-stack:latest   
    container_name: rag_redis
    ports:
      - "6379:6379"
      - "8001:8001"   
    volumes:
      - redis_data:/data
    command: redis-stack-server --save 60 1 --loglevel warning

  qdrant:
    image: qdrant/qdrant:latest
    platform: linux/amd64
    container_name: rag_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  fastapi:
    build: .
    container_name: rag_fastapi
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - qdrant
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - QDRANT_ENDPOINT=http://qdrant:6333

celery_worker:
  build: .
  container_name: rag_celery_worker
  command: celery -A workers.celery_app worker --loglevel=info
  depends_on:
    - redis
    - qdrant
  env_file:
    - .env
  environment:
    - REDIS_URL=redis://redis:6379/0
    - QDRANT_ENDPOINT=http://qdrant:6333

 
  
volumes:
  redis_data:
  qdrant_data: